map1: map1.c read.c tree.c utils.c search.c print.c
	gcc -Wall -o map1 map1.c read.c tree.c utils.c search.c print.c
    
map2: map2.c tree.c read1.c utils.c search.c print.c
	gcc -Wall -o map2 map2.c tree.c read1.c utils.c search.c print.c
    